# Starter pipeline
pool: qa
steps:
- task: BrowserStackResults@1
  inputs:
    browserstackProduct: 'automate'

- task: simplifyqa-pipeline-executor-v2@2
  inputs:
   PIPELINEID: 98
   APIKEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3FhbmV3dWkuc2ltcGxpZnlteWNhcmVlci5jb20iLCJjdXN0b21lcklkIjo0OSwiY29tcGFueU5hbWUiOiJTUUEgVGVzdCIsImxpY2Vuc2VfdHlwZSI6WyJ3ZWIiLCJhbmRyb2lkIiwiaW9zIiwiQVBJIl0sImlhdCI6MTcyNzA5NzcwNywiZXhwIjoxNzU4NjU1MzA3fQ.nZ20hur8UcHwEKcsj1vEvnOzWYZ4GCZn9gbFYBZIudA'
   APIURL: 'https://qanewui.simplifymycareer.com'
   THRESHOLD: 100
   VERBOSE: true